runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /static
    static_files: gs://cv-site1/static
    upload: gs://cv-site1/static/*

  - url: /favicon.ico
    static_files: gs://cv-site1/favicon.ico
    upload: gs://cv-site1/favicon.ico

  - url: /.*
    script: auto
