runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /static
    static_dir: build/static
    http_headers:
      Cache-Control: "public, max-age=31536000"

  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    http_headers:
      Cache-Control: "no-cache"
